#!/bin/bash
#
### BEGIN INIT INFO
# Provides:       sidu-installer-remover 
# Required-Start: $remote_fs
# Required-Stop:  $remote_fs
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Description:    Removes the installer at the first boot.
### END INIT INFO

PATH=$PATH:/bin:/sbin:/usr/sbin

case "$1" in
start)
	if grep "/dev/mapper/siduction-live on /bin" /dev/mounts; then
		echo Removing installer...
		dpkg --purge sidu-installer >>/tmp/sidu-deinstall.log 2>>/tmp/sidu-deinstall.err.log
	fi
status|stop|restart|reload)
	echo "Unsupported command: $1"
    ;;
*)
    ;;
esac

exit 0
