#! /bin/bash
set -e

if ! grep -q "sidu-installer" /etc/hosts ; then
	# if the last newline is missing:
	echo "" >>/etc/hosts
	ADDR=86
	while grep -q "127.0.0.$ADDR" /etc/hosts ; do
		ADDR=$(expr $ADDR + 1)
	done
	echo "127.0.0.$ADDR sidu-installer" >>/etc/hosts
	echo "virtual host installed: sidu-installer ($ADDR)"
fi

# Create the links from the toolkit:
MY_DIR=/usr/share/sidu-installer
pushd $MY_DIR >/dev/null
MY_BACKEND=../sidu-base
function MkLink(){
	if [ ! -L $1 ] ; then
		ln -sf $2/$1 $1
	fi
}
function MkLink2(){
	if [ ! -L $2 ] ; then
		ln -sf $1 $2
	fi
}

# Create the links to the shellserver:
BASE_BACKEND=/usr/share/sidu-base/backend
cd $BASE_BACKEND
MY_BACKEND=../../sidu-installer/backend

MkLink install.sh $MY_BACKEND
MkLink partinfo.pl $MY_BACKEND
MkLink partinfo.sh $MY_BACKEND
MkLink timezoneinfo.sh $MY_BACKEND
MkLink firmware.sh $MY_BACKEND
MkLink firmware.pl $MY_BACKEND
MkLink nonfree.sh $MY_BACKEND
MkLink autopart.sh $MY_BACKEND
MkLink autopart.pl $MY_BACKEND

MkLink2 $BASE_BACKEND/automount-control.sh $MY_BACKEND
MkLink2 /var/cache/sidu-base/public $MY_DIR/installer/static/

pywwetha-control restart
popd >/dev/null

#DEBHELPER#

exit 0
 
