#! /bin/bash
set -e

if ! grep -q "sidu-installer" /etc/hosts ; then
	# if the last newline is missing:
	echo "" >>/etc/hosts
	ADDR=86
	while grep -q "127.0.0.$ADDR" /etc/hosts ; do
		ADDR=$(expr $ADDR + 1)
	done
	echo "127.0.0.$ADDR sidu-installer" >>/etc/hosts
	echo "virtual host installed: sidu-installer ($ADDR)"
fi

# Create the links from the toolkit:
pushd /usr/share/sidu-installer >/dev/null
SRC=../siguibui
function MkLink(){
	if [ ! -L $1 ] ; then
		ln -sf $2/$1 $1
	fi
}
function MkLink2(){
	if [ ! -L $2 ] ; then
		ln -sf $1 $2
	fi
}
MkLink index.php $SRC
MkLink base $SRC

# Create the links to the shellserver:
SRC_INI=/usr/share/siguibui/backend
cd $SRC_INI
SRC=../../sidu-installer/backend
MkLink install.sh $SRC
MkLink partinfo.pl $SRC
MkLink partinfo.sh $SRC
MkLink timezoneinfo.sh $SRC
MkLink firmware.sh $SRC
MkLink firmware.pl $SRC
MkLink nonfree.sh $SRC
MkLink2 $SRC_INI/automount-control.sh $SRC
MkLink2 /var/cache/siguibui/public /usr/share/sidu-installer

popd >/dev/null

#DEBHELPER#

exit 0
 
