#! /bin/bash
set -e
PROJ=sidu-installer
if grep -q $PROJ /etc/hosts ; then
	sed -i -e "/127\.0\.0\.[0-9]*[ \t]*$PROJ/d" /etc/hosts
	echo "virtual host removed: $PROJ"
fi

# delete the links from the sidu-base:
function RmLink(){
	if [ -L $1 ] ; then
		rm -f $1
	fi
}
pushd /usr/share/$PROJ >/dev/null

RmLink installer/static/public
RmLink backend/automount-control.sh

# Remove the links to the shellserver:
cd /usr/share/sidu-base/backend
RmLink install.sh
RmLink partinfo.pl
RmLink partinfo.sh
RmLink timezoneinfo.sh
RmLink firmware.sh
RmLink firmware.pl
RmLink nonfree.sh
RmLink autopart.sh
RmLink autopart.pl

popd >/dev/null

# Debhelpertoken added, review needed

#DEBHELPER#

exit 0
