#! /bin/bash
set -e
PROJ=sidu-installer
if grep -q $PROJ /etc/hosts ; then
	sed -i -e "/127\.0\.0\.[0-9]*[ \t]*$PROJ/d" /etc/hosts
	echo "virtual host removed: $PROJ"
fi

# delete the links from the toolkit:
function RmLink(){
	if [ -L $1 ] ; then
		rm -f $1
	fi
}
pushd /usr/share/$PROJ >/dev/null
RmLink index.php
RmLink base
RmLink public

# Remove the links to the shellserver:
cd /usr/share/siguibui/backend
RmLink install.sh
RmLink partinfo.pl
RmLink partinfo.sh
RmLink timezoneinfo.sh
RmLink firmware.sh
RmLink firmware.pl

popd >/dev/null

# Debhelpertoken added, review needed

#DEBHELPER#

exit 0
