Document: sidu-installer
Title: Debian sidu-installer Manual
Author: <insert document author here>
Abstract: This manual describes what sidu-installer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sidu-installer/sidu-installer.sgml.gz

Format: postscript
Files: /usr/share/doc/sidu-installer/sidu-installer.ps.gz

Format: text
Files: /usr/share/doc/sidu-installer/sidu-installer.text.gz

Format: HTML
Index: /usr/share/doc/sidu-installer/html/index.html
Files: /usr/share/doc/sidu-installer/html/*.html
